### ISSUE TITLE
Database download

### ISSUE THREAD

**Issue by ggabernet** [nf-core/bcellmagic#19]
Currently the database download is a process inside the nexflow pipeline but it is actually also included in the dockerfile as part of container build. 

We would need to decide which one is the best option and just go for one of them.

**Comment by subwaystation** [comment]
I talked to @apeltzer yesterday, and he told me, that we shall leave it to the user:
Either specify a path to the database (which already works for now) or create a nextflow process to do that. But what we not want is that the database is part of the docker image. That would blow it up. Compare to reference genomes for other sequencing pipelines.

**Comment by subwaystation** [comment]
@ggabernet As far as I got it from [main.nf](https://github.com/nf-core/bcellmagic/blob/master/main.nf) the option to download the database within the workflow is already there. So the issue is solved?

**Comment by subwaystation** [comment]
I just discussed with @ggabernet that we need to test this. I will do that.

**Comment by subwaystation** [comment]
Running into
`Pulling Singularity image docker://nfcore/bcellmagic [cache /sfs/7/workspace/ws/afaaj01-bcellmagic-0/work/singularity/nfcore-bcellmagic.img]
ERROR ~ No such variable: ch_igblast_db_for_process_igblast_mix

 -- Check script 'main.nf' at line: 553 or see '.nextflow.log' file for more details
`
I will take a closer look.

**Comment by ggabernet** [comment]
Started working on this as well, I think I solved the issue of the error you were having. Running tests now

**Comment by ggabernet** [comment]
Finished successfully! New PR to nf-core will solve this issue :)

**Comment by ggabernet** [comment]
Will be solved by Pull Request #31. I will close this issue when the PR is merged.
