### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by ggabernet** [nf-core/bcellmagic#26]
- Need to add minimal tests for travis in test.config.
- Use subset of fastq file for one sample.
- Need to remove real primer sequences for fakes.

**Comment by apeltzer** [comment]
Should be fine since https://github.com/nf-core/test-datasets/pull/34 is merged :-), just needs a test profile now 👍

**Comment by ggabernet** [comment]
Will be solved by Pull Request #31. I will close this issue when it is merged.
