### ISSUE TITLE
Add nf-core logo to README.md

### ISSUE THREAD

**Issue by drpatelh** [nf-core/bcellmagic#39]
Just noticed this when trying to get the logo for `bcellmagic`

**Comment by ggabernet** [comment]
Hi @drpatelh , thanks for the remark! So how do I generate the nf-core logo?

**Comment by apeltzer** [comment]
Here you go: https://github.com/nf-core/logos :-)

**Comment by ggabernet** [comment]
I love that there is a container to make the logos 💃

**Comment by apeltzer** [comment]
Let's hope it works 👍 I'm not entirely sure though 😓

**Comment by ggabernet** [comment]
yeah the docker container did not work for me. I edited the svg logo though and that worked fine, will be integrated with the next PR :)
