### ISSUE TITLE
vsearch in dependencies, but usearch called

### ISSUE THREAD

**Issue by fabio-t** [nf-core/bcellmagic#90]
At startup, I got a `vsearch` missing error, and installed that tool. Turns out however that `ClusterSets.py` still uses `usearch`.

I would suggest that either the tools are converted to `vsearch` (possibly the best option?), or that a `usearch` version check is performed at the beginning.

**Comment by ggabernet** [comment]
Hi @fabio-t ,

thanks for using bcellmagic. Could you share the command how you are running the pipeline?

The pipeline comes with the option to run using both docker containers and singularity containers, which have all of the tools already installed that are needed for the analysis. 

Running the pipeline tests with docker would be for example like this:
```
nextflow run nf-core/bcellmagic -profile test,docker
```

For your other analysis, you can run the pipeline using:
```
nextflow run nf-core/bcellmagic -profile docker <add any further parameters here>
```

**Comment by fabio-t** [comment]
Hi,

I'm currently running it like this:

```
nextflow run nf-core/bcellmagic --metadata metadata.csv --vprimers cprimers.fasta --cprimers vprimers.fasta --umi_position R1 --umi-length 12 --max_memory 8.GB --max_cpus 4
```

Note how I've had to invert vprimers and cprimers, because in our data, R1 contains the UMI and the V-primer, while R2 contains the C-primer (and down to the CDR3 and rest of v region).

I've solved the `vsearch` issue by making a symlink, no big deal but `ClusterSets.py` should be updated to use `vsearch` instead of `usearch` :)

**Comment by ggabernet** [comment]
Hi Fabio,

it is highly recommended to run the pipeline with containers, to ensure that your results will be reproducible and will not depend on the versions of the tools that you install locally. Therefore you can run the pipeline like this after [installing docker](https://docs.docker.com/get-docker/).

```
nextflow run nf-core/bcellmagic -profile docker --metadata metadata.csv --vprimers cprimers.fasta --cprimers vprimers.fasta --umi_position R1 --umi-length 12 --max_memory 8.GB --max_cpus 4
```

Additionally, this memory setting should be fine to run small datasets but to run a full analysis you'll have higher memory requirements.

I'll add your problem with R1 /R2 and the primers as another issue, thanks for the feedback!

Do not hesitate to ask if you have any other questions when running the pipeline. You can also join us on the nf-core slack `https://nfcore.slack.com/archives/bcellmagic` for further questions on getting the pipeline to run for your data.

**Comment by ggabernet** [comment]
Ah related to the original problem of `usearch` versus `vsearch`, It's true that ClustersSets.py should be updated. This is part of the pRESTO toolset, so it is an issue of that tool. In bcellmagic, the docker container has a symlink of usearch to vsearch to circumvent the problem just as you did locally.

**Comment by fabio-t** [comment]
I see, thanks!

**Comment by ggabernet** [comment]
I'll close this issue then, please reopen or open a new issue if you have other issues!
