### ISSUE TITLE
BCELLMAGIC: Convert all parameter docs to JSON schema

### ISSUE THREAD

**Issue by apeltzer** [nf-core/bcellmagic#91]
Hi!

this is not necessarily an issue with the pipeline, but in order to streamline the documentation group next week for the hackathon, I'm opening issues in all repositories / pipeline repos that might need this update to switch from parameter docs to auto-generated documentation based on the JSON schema.

This will then supersede any further parameter documentation, thus making things a bit easier :-)

If this doesn't apply (anymore), please close the issue. Otherwise, I'm hoping to have some helping hands on this next week in the documentation team on Slack https://nfcore.slack.com/archives/C01QPMKBYNR

**Comment by ggabernet** [comment]
Hi Alex,

this is already done in the `dev` version of the pipeline. So I'll close the issue :)

**Comment by apeltzer** [comment]
Even better - I just opened issues to keep track of these things for next week and didn't want to check each dev branch ;-)

**Comment by ggabernet** [comment]
sure, of course, great idea :)
