### ISSUE TITLE
Add flexibility cprimers / vprimers in R1 or R2

### ISSUE THREAD

**Issue by ggabernet** [nf-core/bcellmagic#92]
As reported by @fabio-t , the pipeline currently expects `C-region` primers to be in the R1 fastq and `V-region` primers to be in the R2 fastq. 

Better docs about this or the possibility of specifying R1/R2 for both primers would be needed.

**Comment by ggabernet** [comment]
Hi @fabio-t, 
I'm working on that at the moment, to make sure that I understand your sequencing protocol and I can include it:
- Do you use PCR amplification? Or another protocol such as RACE-5'?
- Does your primer constructs look like that but the V primers in the R2 reads instead?
- Do you use UMIs in your protocol? And if so, do you read them with the indices or are they included in one of the primers?
If you have a short drawing of your construct that would be of course fabulous!
<img width="347" alt="Screenshot 2021-04-30 at 10 10 11" src="https://user-images.githubusercontent.com/3973503/116667769-d9437080-a99c-11eb-89bf-f508b0935da7.png">

**Comment by fabio-t** [comment]
This is the protocol used: https://www.nature.com/articles/nprot.2016.093

Yes, generally it looks like that and yes, we use UMIs (12-bp). This is the barcode pattern I use in MIGEC for UMI demultiplexing: `CAGTggtatcaacgcaGAGTNNNNtNNNNtNNNNtct`

I'm attaching a few hundred reads from one of our samples (mouse, IGH). Maybe this can be helpful? https://file.io/5DjlWUpZ7kjh

**Comment by fabio-t** [comment]
Example result from IMGT V-quest:

R1:
![image](https://user-images.githubusercontent.com/5008927/117568438-7f3f5b00-b0c0-11eb-9ecb-4f72e0f3a687.png)

R2:
![image](https://user-images.githubusercontent.com/5008927/117568488-d04f4f00-b0c0-11eb-8cb4-d069979b7859.png)

**Comment by fabio-t** [comment]
For convenience, this is the cprimer at the beginning of R2: `ATTGGGCAGCCCTGATTTCAGTGGGTAGATGGTG`

**Comment by ggabernet** [comment]
Hi @Fabio-t, 

thanks a lot for all the info. I've added a fix for this, I will double check that it should work for you and fix another issue, and then you should be able to test the pipeline running the `dsl2` branch with `-r dsl2`. Will keep you updated :)

**Comment by ggabernet** [comment]
This has been added to the `2.0.0` release
