### ISSUE TITLE
MakeDb igblast missing light chain reference germlines

### ISSUE THREAD

**Issue by ssnn-airr** [nf-core/bcellmagic#98]
The script part in process [`CHANGEO_MAKEDB`](https://github.com/nf-core/bcellmagic/blob/1980e717e4b19dc18dac840ed0f4cdcdbdc71244/modules/local/process/changeo_makedb.nf#L30:L53) can be simplified by providing a folder path to `-r`, not all individual `fasta` files: 
`-r  ${imgt_base}/${params.species}/vdj/`. This would also fix a bug where Ig light chain reference germlines (IGKV, IGKJ, IGLV, IGLJ) are not being passed to `-r`.

**Comment by ggabernet** [comment]
Hi @ssnn-airr, thanks for filing this issue. I will solve it in the next version!

**Comment by ggabernet** [comment]
Solved by #109 and added to latest release `2.0.0`
